[project]
name = "trays"
version = "0.1.0"
description = "Backend application for creating laser cut trays"
authors = [
    { name = "Greg Skluzacek", email = "gskluzacek@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

# uv sync
# uv add --group dev pytest

[dependency-groups]
dev = [
    "ruff>=0.14.14",
    "pytest>=9.0.2",
    "coverage>=7.13.1",
]

[tool.ruff]
line-length = 125
